const {test,expect}=require('@playwright/test');
const {pathToFileURL}=require('node:url');
const path=require('node:path'),fs=require('node:fs');
test('custom colors are shared, survive disk and local storage, and render in exports and parts lists',async({page})=>{
 await page.goto(pathToFileURL(path.resolve('index.html')).href);
 await page.locator('#filament-family').selectOption('custom');
 await expect(page.locator('#swatches button')).toHaveCount(0);
 await page.locator('#add-custom-color').click();
 await page.locator('#custom-color-name').fill('Walnut test');
 await page.locator('#custom-color-hex').fill('#123456');
 await page.locator('#custom-color-form button[type=submit]').click();
 await expect(page.locator('#color-name')).toHaveText('Walnut test');
 await page.locator('#select-all').click();
 await page.locator('[data-pattern="1"]').click();
 await expect(page.locator('#board [data-insert]').first()).toHaveAttribute('fill','#123456');
 await page.locator('#board-filament').click();await page.locator('#frame-color-family').selectOption('custom');await page.locator('#frame-swatches [aria-label="Walnut test · #123456"]').click();await page.keyboard.press('Escape');
 await page.locator('#empty-filament').click();await page.locator('#frame-color-family').selectOption('basic');await page.locator('#frame-swatches [aria-label="Cocoa Brown · #6F5034"]').click();await page.keyboard.press('Escape');
 const downloadPromise=page.waitForEvent('download');await page.locator('#save').click();
 const download=await downloadPromise,raw=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 expect(raw.customColors).toHaveLength(1);expect(raw.customColors[0].name).toBe('Walnut test');
 expect(raw.config.boardColor).toBe('#123456');expect(raw.config.emptyColor).toBe('#6F5034');
 await page.reload();await expect(page.locator('#color-name')).toHaveText('Walnut test');
 await page.locator('#file').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(raw))});
 await page.locator('#print-parts').click();
 await expect(page.locator('#parts-report')).toContainText('Walnut test');
 await expect(page.locator('#parts-report')).toContainText('Custom');
 await page.locator('#close-parts').click();
 const svgPromise=page.waitForEvent('download');await page.locator('#export-svg').click();
 const svg=await svgPromise;expect(fs.readFileSync(await svg.path(),'utf8')).toContain('#123456');
 await page.locator('#empty-filament').click();await page.locator('#frame-add-custom').click();
 await page.locator('#custom-color-name').fill('Mist');await page.locator('#custom-color-hex').fill('#abcdef');
 await page.locator('#custom-color-form button[type=submit]').click();
 await expect(page.locator('#empty-color')).toHaveValue('#abcdef');
 await page.locator('#undo').click();await expect(page.locator('#empty-color')).toHaveValue('#6f5034');
 await page.locator('#redo').click();await expect(page.locator('#empty-color')).toHaveValue('#abcdef');
 await page.locator('#filament-family').selectOption('custom');await expect(page.locator('#swatches button')).toHaveCount(2);
});
