const {test,expect}=require('@playwright/test');const {pathToFileURL}=require('node:url');const path=require('node:path');
const url=pathToFileURL(path.resolve(__dirname,'../../index.html')).href;
test.beforeEach(async({page})=>{await page.goto(url);});
test('starts offline, renders catalog and persists a batch placement',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await expect(page.locator('.pattern')).toHaveCount(41);await page.locator('#select-all').click();await page.locator('[data-pattern="8"]').click();const count=await page.locator('.cell-hit').count();const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('kumiko-studio.design.v1')));expect(Object.keys(data.inserts)).toHaveLength(count);await page.reload();await expect(page.locator('#piece-count')).toContainText(`${count} inserts`);await page.screenshot({path:'tests/browser/desktop.png',fullPage:true});expect(errors).toEqual([]);});
test('undo and redo, clearing, orientation changes and round-trip validation',async({page})=>{await page.locator('#select-all').click();await page.locator('[data-pattern="1"]').click();await page.locator('#clear').click();await expect(page.locator('#piece-count')).toContainText('0 inserts');await page.locator('#undo').click();await expect(page.locator('#piece-count')).not.toContainText(/^0 inserts/);await page.locator('#redo').click();await expect(page.locator('#piece-count')).toContainText('0 inserts');await page.locator('#undo').click();await page.locator('[data-orientation="vertex-corners"]').click();expect(await page.evaluate(()=>!!KumikoGeometry.validate(JSON.parse(localStorage.getItem('kumiko-studio.design.v1'))))).toBe(true);});
test('drag drop highlights and fills one or all selected cells',async({page})=>{const target=page.locator('.cell-hit').nth(10);const dt=await page.evaluateHandle(()=>new DataTransfer());await page.locator('[data-pattern="3"]').dispatchEvent('dragstart',{dataTransfer:dt});await target.dispatchEvent('dragover',{dataTransfer:dt});await expect(target).toHaveClass(/drop-target/);await target.dispatchEvent('drop',{dataTransfer:dt});await expect(page.locator('#piece-count')).toContainText('1 inserts');await page.locator('#select-all').click();await page.locator('[data-pattern="5"]').dispatchEvent('dragstart',{dataTransfer:dt});await target.dispatchEvent('dragover',{dataTransfer:dt});expect(await page.locator('.drop-target').count()).toBe(await page.locator('.cell-hit').count());await target.dispatchEvent('drop',{dataTransfer:dt});const ids=await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('kumiko-studio.design.v1')).inserts).map(x=>x.patternId));expect(ids.every(x=>x===5)).toBe(true);});
test('box selection and command-click are additive',async({page})=>{const locs=await page.evaluate(()=>[10,20].map(i=>{const poly=document.querySelectorAll('.cell-hit')[i],pts=[...poly.points],p=new DOMPoint(pts.reduce((s,p)=>s+p.x,0)/pts.length,pts.reduce((s,p)=>s+p.y,0)/pts.length).matrixTransform(document.querySelector('#board').getScreenCTM());return{x:p.x,y:p.y};}));await page.mouse.click(locs[0].x,locs[0].y);await page.keyboard.down('Meta');await page.mouse.click(locs[1].x,locs[1].y);await page.keyboard.up('Meta');await expect(page.locator('.selected')).toHaveCount(2);await page.locator('#deselect').click();const box=await page.locator('#canvas').boundingBox();await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+box.height/2,{steps:8});await page.mouse.up();expect(await page.locator('.selected').count()).toBeGreaterThan(2);});
test('invalid imports preserve design and valid imports can be undone',async({page})=>{await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await expect(page.locator('#toast')).toContainText('Could not load');await page.locator('#name').fill('Saved test');await page.locator('#name').blur();const data=await page.evaluate(()=>localStorage.getItem('kumiko-studio.design.v1'));await page.locator('#name').fill('Other test');await page.locator('#name').blur();await page.locator('#file').setInputFiles({name:'design.json',mimeType:'application/json',buffer:Buffer.from(data)});await expect(page.locator('#name')).toHaveValue('Saved test');await page.locator('#undo').click();await expect(page.locator('#name')).toHaveValue('Other test');const download=page.waitForEvent('download');await page.locator('#save').click();expect((await download).suggestedFilename()).toBe('Other-test.kumiko.json');});
test('parts checklist itemizes design and color, omits empty, and prints only the report',async({page})=>{await page.locator('#select-all').click();await page.locator('[data-pattern="8"]').click();await page.locator('#deselect').click();await page.locator('.cell-hit').nth(10).focus();await page.keyboard.press('Enter');await page.locator('[aria-label="Terracotta · #B15533"]').click();await page.locator('[data-pattern="8"]').click();await page.locator('#deselect').click();await page.locator('.cell-hit').nth(12).focus();await page.keyboard.press('Enter');await page.locator('[data-pattern="0"]').click();await page.locator('#print-parts').click();await expect(page.locator('#parts-dialog')).toBeVisible();await expect(page.locator('#parts-report .parts-checklist tbody tr')).toHaveCount(2);const preview=page.locator('#parts-report .report-preview');await expect(preview).toBeVisible();expect(await preview.evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);const previewSvg=await preview.evaluate(img=>decodeURIComponent(img.src.split(',')[1]));expect(previewSvg).toContain('#B15533');expect(previewSvg).not.toContain('cell-hit');await expect(page.locator('#parts-report')).toContainText('Bone White');await expect(page.locator('#parts-report')).toContainText('Terracotta');await expect(page.locator('#parts-report .parts-checklist tbody')).not.toContainText('#0');const total=await page.locator('#parts-report .parts-checklist tfoot td').last().textContent();expect(Number(total)).toBe((await page.locator('.cell-hit').count())-1);await page.evaluate(()=>window.print=()=>{window.didPrint=true;window.dispatchEvent(new Event('beforeprint'));});await page.locator('#print-sheet').click();expect(await page.evaluate(()=>window.didPrint)).toBe(true);await page.emulateMedia({media:'print'});await expect(page.locator('main')).toBeHidden();await expect(page.locator('#parts-report')).toBeVisible();await expect(page.locator('.report-toolbar')).toBeHidden();await page.screenshot({path:'tests/browser/parts-list.png',fullPage:true});});
test('empty parts list, SVG export and narrow layout',async({page})=>{await page.locator('#print-parts').click();await expect(page.locator('#parts-report')).toContainText('No inserts placed');await page.locator('#close-parts').click();const download=page.waitForEvent('download');await page.locator('#export-svg').click();expect((await download).suggestedFilename()).toBe('Untitled-panel.svg');await page.setViewportSize({width:390,height:844});await page.locator('button[data-panel="palette"]').click();await expect(page.locator('#patterns')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'tests/browser/mobile.png',fullPage:true});});
test('STL patterns replace traces, preserve openings and align inside lattice',async({page})=>{
 await expect(page.locator('[data-pattern="1"]')).not.toContainText('STL');
 await expect(page.locator('[data-pattern="2"]')).not.toContainText('STL');
 await expect(page.locator('[data-pattern="3"]')).not.toContainText('STL');
 await page.locator('#pitch').fill('50');await page.locator('#pitch').blur();
 await page.locator('#select-all').click();await page.locator('[data-pattern="3"]').click();
 expect(await page.evaluate(()=>{
  const config=JSON.parse(localStorage.getItem('kumiko-studio.design.v1')).config;
  const cell=KumikoGeometry.board(config).cells[0];
  const expected=KumikoGeometry.pathData(KumikoCatalog.patterns.find(p=>p.id===3),KumikoGeometry.insetTriangle(cell.triangle,1.5),0,config);
  return document.querySelector('#board g path').getAttribute('d')===expected;
 })).toBe(true);
 await page.locator('#deselect').click();await page.screenshot({path:'tests/browser/stl-board.png',fullPage:true});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../../previews/stl-inserts.svg')).href);
 await page.screenshot({path:'previews/stl-inserts.png'});
});
test('all designs are available with glue warnings and no rectangular click focus',async({page})=>{
 await expect(page.locator('.pattern')).toHaveCount(41);
 await expect(page.locator('.glue-warning')).toHaveCount(6);
 for(const id of [10,11,12,13,16,40]){
  const badge=page.locator(`[data-pattern="${id}"] .glue-warning`);
  await badge.hover();await expect(badge).toBeVisible();await expect(badge).toHaveAttribute('title',/Requires glue/);
 }
 await expect(page.locator('[data-pattern="0"] .glue-warning')).toHaveCount(0);
 await page.locator('#select-all').click();await page.locator('[data-pattern="40"]').click();
 await page.locator('#print-parts').click();await expect(page.locator('#parts-report')).toContainText('Requires glue');await page.locator('#close-parts').click();
 await page.locator('#deselect').click();
 const point=await page.evaluate(()=>{const poly=document.querySelectorAll('.cell-hit')[10],pts=[...poly.points];const p=new DOMPoint(pts.reduce((s,p)=>s+p.x,0)/pts.length,pts.reduce((s,p)=>s+p.y,0)/pts.length).matrixTransform(document.querySelector('#board').getScreenCTM());return{x:p.x,y:p.y};});
 await page.mouse.click(point.x,point.y);await expect(page.locator('.cell-hit.selected')).toHaveCount(1);
 expect(await page.locator('#board').evaluate(el=>getComputedStyle(el).outlineStyle)).toBe('none');
 expect(await page.locator('#board').evaluate(el=>getComputedStyle(el).webkitTapHighlightColor)).toBe('rgba(0, 0, 0, 0)');
 await page.locator('.cell-hit').nth(10).focus();await page.keyboard.press('Enter');await expect(page.locator('.cell-hit.selected')).toHaveCount(1);
});
